GET http://localhost:1337/facdashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidHZlMjBjczAwMCIsImlhdCI6MTY4NTA4MjAyNywiZXhwIjoxNjg1MDgyMDY3fQ.sL9y5tMe2Jr0kQVd-XfTGRCwEuchKY6DkhGhGQZFjsY

###
DELETE http://localhost:1337/logout
Content-Type: application/json

  {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidHZlMjBjczAwMCIsImlhdCI6MTY4NTA4NzY4MH0.2RpKOo0ZDytgladEsr5WgyuKdLP3AxcsYbfjxtuXERc"
  }

###
POST http://localhost:1337/tokens 
content-Type : application/json

  {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidHZlMjBjczAwMCIsImlhdCI6MTY4NTA4NzY4MH0.2RpKOo0ZDytgladEsr5WgyuKdLP3AxcsYbfjxtuXERc"
  }

###
POST http://localhost:1337/login
content-Type : application/json
 
 {
   "ktuId": "tve20cs000",
   "password": "0000"
 }

###

